api:
  autodiscoveryId: "123456"  

http:
 listener:
  host: "0.0.0.0"
  port: "8087"
  timeout: "30000"
  
https:
  host: "0.0.0.0"
  port: "8082"
  
tls:
  type: "JKS"
  path: "iewc-SSL-Keystore.jks"
  alias: "*.esb.internal.iewc.com"
  keypassword: test123
  password: test123

sap:
  username: "s_mule"
  messageserverhost: "sapr3x01.iewc.com"
  systemid: "R3X"
  messageserverport: "3608"
  messagingservergroupname: "STANDARD"
  sapsystemnumber: "00"
  sapclientid: "010"
  
  
